server {
    listen 80 default_server;
    listen 443 ssl default_server;
    http2 on;
    server_name _;

    ssl_certificate     /etc/nginx/ssl/default/default.crt;
    ssl_certificate_key /etc/nginx/ssl/default/default.key;

    return 444; 
}
